version: '3'

services:

  mysql.data:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123

  identity.api:
    build:
      context: .
      dockerfile: src/server/services/identity/api/Dockerfile
    ports:
      - "5001:80"
    restart: always
    depends_on:
      - mysql.data